=== rupertlssmith/jenerator/configurator/src/resources/config-beans.xsd
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Rupert Smith (Liberty Bishop 1151 Ltd.) -->
<!--
 Defines the schema for XML files that contain a 'config beans' configuration set up. This consists of a series of 
 elements, one for each bean, that specifies a config bean and its set up parameters. 

 Typically these beans are loaded at application start up time (but this does not have to be the case, config beans are
 also designed to be re-configurable on the fly). The beans are loaded, their set up parameters are set and their
 doConfigure methods are called.
 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cb="http://thesett.com/config-beans-0.1" targetNamespace="http://thesett.com/config-beans-0.1" elementFormDefault="qualified">
    <!-- The configBeans root element must have at least one config bean definition. -->
    <xs:element name="configBeans">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="cb:jndiConfig"/>
                <xs:element ref="cb:beanSetup" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!--
  A beanSetup definition must specify the class name of the config bean and optionally any set up parameters that are
  to be set on the bean.
  -->
    <xs:element name="beanSetup">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="cb:setUpProperty" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="beanClassName" type="xs:string" use="required"/>
            <xs:attribute name="force" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>
    <!-- A setUpProperty specifies the name and value pair of a config beans property. The values are strings but
      these will be parsed into the correct type by using introspection on the bean to determine what the correct
      type is. Configuration should fail if the data cannot be converted from the string to the correct type. -->
    <xs:element name="setUpProperty">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="jndiConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="cb:property" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="property">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="value" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rupertlssmith/jenerator/configurator/src/unittests/com/thesett/common/config/test_config.xml
<configBeans xmlns="http://thesett.com/config-beans-0.1" 
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://thesett.com/config-beans-0.1 C:\DOCUME~1\Rupert\projects\configurator\src\resources\config-beans.xsd">
                       
    <jndiConfig>
        <property name="java.naming.factory.initial" value="com.thesett.common.jndi.SimpleInitialContextFactory"/>
    </jndiConfig>
    
    <beanSetup beanClassName="com.thesett.common.config.TestConfigBean" force="false">
        <setUpProperty name="testInt" value="1"/>
        <setUpProperty name="testByte" value="1"/>
        <setUpProperty name="testChar" value="a"/>
        <setUpProperty name="testLong" value="128000000000"/>
        <setUpProperty name="testBoolean" value="true"/>
        <setUpProperty name="testFloat" value="1.23456789"/>
        <setUpProperty name="testDouble" value="1.23456789123456789123456789"/>
        <setUpProperty name="testString" value="Test"/>
    </beanSetup>
    
</configBeans>

=== rupertlssmith/jenerator/catalogue-manager/src/test-resources/testconfig.xml
<configBeans xmlns="http://thesett.com/config-beans-0.1"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://thesett.com/config-beans-0.1 config-beans.xsd">

  <jndiConfig>
    <property name="java.naming.factory.initial" value="com.thesett.common.jndi.SimpleInitialContextFactory"/>
  </jndiConfig>

  <!-- Set up the mode config bean to use development mode. -->
  <beanSetup beanClassName="com.thesett.catalogue.config.ModeConfigBean">
    <setUpProperty name="devMode" value="true"/>
  </beanSetup>

  <!-- Set up the loader config bean to load the test catalogue model. -->
  <beanSetup beanClassName="com.thesett.catalogue.config.ModelLoaderConfigBean">
    <setUpProperty name="modelResource" value="test-catalogue.xml"/>
  </beanSetup>

  <!-- Set up the hibernate config bean to configure hibernate on the generated mapping for the model. -->
  <beanSetup beanClassName="com.thesett.catalogue.config.HibernateConfigBean">
    <setUpProperty name="mappingResource" value="test-catalogue.hbm.xml"/>
    <!-- The same hibernate properties are used for the catalogue config bean and manager service. -->
    <setUpProperty name="propertiesResource" value="test-hibernate.properties"/>
    <setUpProperty name="secondaryPropertiesResource" value="test-hibernate.properties"/>
  </beanSetup>

  <!-- Set up the index config bean to prepare the index for handling the test model. -->
  <beanSetup beanClassName="com.thesett.index.config.IndexStoreConfigBean">
    <setUpProperty name="resourceName" value="test-index-config.xml"/>
  </beanSetup>

  <!-- Set up the catalogue config bean to prepare the catalogue and check the model against the database. -->
  <beanSetup beanClassName="com.thesett.catalogue.config.CatalogueConfigBeanImpl">
    <setUpProperty name="modelPackage" value="com.thesett.catalogue.example"/>
  </beanSetup>

</configBeans>

=== rupertlssmith/jenerator/catalogue-ejb-test/src/test-resources/catalogue-ejb-test-config.xml
<configBeans xmlns="http://thesett.com/config-beans-0.1"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://thesett.com/config-beans-0.1 C:\DOCUME~1\Rupert\projects\configurator\src\resources\config-beans.xsd">

  <!-- Use JBoss JNDI to deposit the config beans into. -->
  <jndiConfig>
    <property name="java.naming.factory.initial" value="org.jnp.interfaces.NamingContextFactory"/>
    <property name="java.naming.factory.url.pkgs" value="org.jboss.naming:org.jnp.interfaces"/>
    <property name="java.naming.provider.url" value="localhost"/>
  </jndiConfig>

  <!-- Set up the service locator config bean so that EJB services can be found. -->
  <beanSetup beanClassName="com.thesett.common.locator.ServiceLocatorConfigBean">
    <setUpProperty name="contextName" value="local"/>
  </beanSetup>

  <!-- Set up the mode config bean to use development mode. -->
  <beanSetup beanClassName="com.thesett.catalogue.config.ModeConfigBean">
    <setUpProperty name="devMode" value="true"/>
  </beanSetup>

  <!-- Set up the loader config bean to load the test catalogue model. -->
  <beanSetup beanClassName="com.thesett.catalogue.config.ModelLoaderConfigBean">
    <setUpProperty name="modelResource" value="test-catalogue.xml"/>
  </beanSetup>

  <!-- Set up the hibernate config bean to configure hibernate on the generated mapping for the model. -->
  <beanSetup beanClassName="com.thesett.catalogue.config.HibernateConfigBean">
    <setUpProperty name="mappingResource" value="test-catalogue.hbm.xml"/>
    <!-- CMT bound session factory is used for the catalogue service, non CMT for the configurator code. -->
    <setUpProperty name="propertiesResource" value="catalogue-ejb-test-hibernate.properties"/>
    <setUpProperty name="secondaryPropertiesResource" value="catalogue-ejb-test-hibernate-non-cmt.properties"/>
  </beanSetup>

  <!-- Set up the index config bean to prepare the index for handling the test model. -->
  <beanSetup beanClassName="com.thesett.index.config.IndexStoreConfigBean">
    <setUpProperty name="resourceName" value="test-index-config.xml"/>
  </beanSetup>

  <!-- Set up the catalogue config bean to prepare the catalogue and check the model against the database. -->
  <beanSetup beanClassName="com.thesett.catalogue.config.CatalogueConfigBeanImpl">
    <setUpProperty name="modelPackage" value="com.thesett.catalogue.example"/>
  </beanSetup>

</configBeans>
