=== rupertlssmith/jenerator/javasource/src/resources/tl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Rupert Smith (Liberty Bishop 1151 Ltd.) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <!--Schema for the code generation template language (tl).-->
    <xs:element name="tl">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="tlroot" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="tlroot" type="tlrootType" abstract="true"/>
    <xs:complexType name="tlrootType" mixed="true">
        <xs:sequence>
            <xs:element ref="tlroot" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="for" type="forType" substitutionGroup="tlroot"/>
    <xs:complexType name="forType">
        <xs:complexContent>
            <xs:extension base="tlrootType">
                <xs:attribute name="path" type="xs:string"/>
                <xs:attribute name="var" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="if" type="ifType" substitutionGroup="tlroot"/>
    <xs:complexType name="ifType">
        <xs:complexContent>
            <xs:extension base="tlrootType">
                <xs:attribute name="path" type="xs:string"/>
                <xs:attribute name="whitespace" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="java" type="javaType" substitutionGroup="tlroot"/>
    <xs:complexType name="javaType">
        <xs:complexContent>
            <xs:extension base="tlrootType"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="declarations" type="declarationsType" substitutionGroup="tlroot"/>
    <xs:complexType name="declarationsType">
        <xs:complexContent>
            <xs:extension base="tlrootType"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="expr" type="exprType" substitutionGroup="tlroot"/>
    <xs:complexType name="exprType">
        <xs:complexContent>
            <xs:extension base="tlrootType"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="value" type="valueType" substitutionGroup="tlroot"/>
    <xs:complexType name="valueType">
        <xs:complexContent>
            <xs:extension base="tlrootType">
                <xs:attribute name="path" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="empty" type="emptyType" substitutionGroup="tlroot"/>
    <xs:complexType name="emptyType">
        <xs:complexContent>
            <xs:extension base="tlrootType"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="compilationUnit" type="compilationUnitType" substitutionGroup="tlroot"/>
    <xs:complexType name="compilationUnitType">
        <xs:complexContent>
            <xs:extension base="tlrootType">
                <xs:attribute name="package" type="xs:string" use="required"/>
                <xs:attribute name="fileName" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="var" type="varType" substitutionGroup="tlroot"/>
    <xs:complexType name="varType">
        <xs:complexContent>
            <xs:extension base="tlrootType">
                <xs:attribute name="name" type="xs:string" use="required"/>
                <xs:attribute name="value" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== rupertlssmith/jenerator/catalogue-maven-plugin/src/resources/catalogue-view-interface.xml
<?xml version="1.0"?>
<tl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="C:\Documents and Settings\Rupert\projects\javasource\src\resources\tl.xsd"
    xmlns:cat="http://thesett.com/catalogue-def-0.2"
    xmlns:gen="http://thesett.com/source-code-generator-0.1">

<var name="package" value="cat:CatalogueDefinition/cat:Package/@name"/>

<for path="cat:CatalogueDefinition/cat:ViewDef">
<compilationUnit package="$package" fileName="gen:toCamelCaseUpper(concat(string(@name), '.java'))">
package <value path="$package"/>;

import java.util.Date;
import java.io.Serializable;

import org.apache.log4j.Logger;

import com.thesett.aima.state.ComponentType;
import com.thesett.aima.state.OrdinalAttribute;
import com.thesett.aima.attribute.impl.HierarchyAttribute;
import com.thesett.aima.attribute.impl.EnumeratedStringAttribute;
import com.thesett.catalogue.interfaces.*;
import com.thesett.catalogue.core.*;
import com.thesett.common.error.NotImplementedException;

/**
 * Generated view interface from catalogue model.
 */
public interface <value path="gen:toCamelCaseUpper(string(@name))"/> extends ViewInstance
{
    Long getId();
    void setId(Long id);

    <for path="cat:Integer">
    public int get<value path="gen:toCamelCaseUpper(string(@name))"/>();

    public void set<value path="gen:toCamelCaseUpper(string(@name))"/>(int <value path="gen:toCamelCase(string(@name))"/>);
    </for>

    <for path="cat:Real">
    public float get<value path="gen:toCamelCaseUpper(string(@name))"/>();

    public void set<value path="gen:toCamelCaseUpper(string(@name))"/>(float <value path="gen:toCamelCase(string(@name))"/>);
    </for>

    <for path="cat:String">
    public String get<value path="gen:toCamelCaseUpper(string(@name))"/>();

    public void set<value path="gen:toCamelCaseUpper(string(@name))"/>(String <value path="gen:toCamelCase(string(@name))"/>);
    </for>

    <for path="cat:Date">
    public Date get<value path="gen:toCamelCaseUpper(string(@name))"/>();

    public void set<value path="gen:toCamelCaseUpper(string(@name))"/>(Date <value path="gen:toCamelCase(string(@name))"/>);
    </for>

    <for path="cat:Time">
    public long get<value path="gen:toCamelCaseUpper(string(@name))"/>();

    public void set<value path="gen:toCamelCaseUpper(string(@name))"/>(long <value path="gen:toCamelCase(string(@name))"/>);
    </for>

    <for path="cat:Enumeration">
    public void set<value path="gen:toCamelCaseUpper(string(@name))"/>(EnumeratedStringAttribute <value path="gen:toCamelCase(string(@name))"/>);
    </for>

    <for path="cat:Hierarchy">
    public <value path="gen:toCamelCaseUpper(string(@type))"/> get<value path="gen:toCamelCaseUpper(string(@name))"/>();
    public void set<value path="gen:toCamelCaseUpper(string(@name))"/>(HierarchyAttribute <value path="gen:toCamelCase(string(@name))"/>);
    public void set<value path="gen:toCamelCaseUpper(string(@name))"/>(<value path="gen:toCamelCaseUpper(concat(string(@type), ' '))"/> <value path="gen:toCamelCase(string(@name))"/>);

    </for>

    <for path="cat:Component">
    public <value path="gen:toCamelCaseUpper(string(@type))"/> get<value path="gen:toCamelCaseUpper(string(@name))"/>();

    public void set<value path="gen:toCamelCaseUpper(string(@name))"/>(<value path="gen:toCamelCaseUpper(concat(string(@type), ' '))"/> <value path="gen:toCamelCase(string(@name))"/>);
    </for>
}

</compilationUnit>
</for>
</tl>

=== rupertlssmith/jenerator/catalogue-maven-plugin/src/resources/catalogue-hierarchy-bean.xml
<?xml version="1.0"?>
<tl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="C:\Documents and Settings\Rupert\projects\javasource\src\resources\tl.xsd"
    xmlns:cat="http://thesett.com/catalogue-def-0.2"
    xmlns:gen="http://thesett.com/source-code-generator-0.1">

<var name="package" value="cat:CatalogueDefinition/cat:Package/@name"/>

<for path="cat:CatalogueDefinition/cat:HierarchyDef">
<compilationUnit package="$package" fileName="gen:toCamelCaseUpper(concat(string(@name), '.java'))">
package <value path="$package"/>;

import java.io.Serializable;

import org.apache.log4j.Logger;

import com.thesett.aima.attribute.impl.HierarchyAttribute;
import com.thesett.aima.state.impl.ExtendableBeanState;

/**
 * Generated hierarchy bean from catalogue model.
 */
public class <value path="gen:toCamelCaseUpper(string(@name))"/> extends ExtendableBeanState implements Serializable
{
    /** Used for logging. */
    private static final Logger log = Logger.getLogger(<value path="gen:toCamelCaseUpper(string(@name))"/>.class);

    private HierarchyAttribute <value path="gen:toCamelCase(string(@name))"/>;

    /** No-arg constructor for serialization. */
    public <value path="gen:toCamelCaseUpper(string(@name))"/>() {}

    public <value path="gen:toCamelCaseUpper(string(@name))"/>(HierarchyAttribute h) { this.<value path="gen:toCamelCase(string(@name))"/> = h; }

    public <value path="gen:toCamelCaseUpper(string(@name))"/>(<for path=".//cat:Level">String <value path="@name"/><if path="gen:notLastInFor()">, </if></for>)
    {
        HierarchyAttribute.HierarchyAttributeFactory factory = HierarchyAttribute.getFactoryForClass("<value path="@name"/>");

        <value path="gen:toCamelCase(string(@name))"/> = factory.createHierarchyAttribute(new String[] { <for path=".//cat:Level"><value path="@name"/><if path="gen:notLastInFor()">, </if></for> });
    }

    private Long getId()
    {
        if (<value path="gen:toCamelCase(string(@name))"/> != null)
        {
            return <value path="gen:toCamelCase(string(@name))"/>.getId();
        }
        else
        {
            return null;
        }
    }

    private void setId(Long id)
    {
        if (<value path="gen:toCamelCase(string(@name))"/> != null)
        {
            <value path="gen:toCamelCase(string(@name))"/>.setId(id);
        }
    }

    public HierarchyAttribute get<value path="gen:toCamelCaseUpper(string(@name))"/>()
    {
        return <value path="gen:toCamelCase(string(@name))"/>;
    }

    public void set<value path="gen:toCamelCaseUpper(string(@name))"/>(HierarchyAttribute h)
    {
        <value path="gen:toCamelCase(string(@name))"/> = h;
    }

    public boolean equals(Object o)
    {
        log.debug("public boolean equals(Object o): called");

        if (o instanceof <value path="gen:toCamelCaseUpper(string(@name))"/>)
        {
            <value path="gen:toCamelCaseUpper(string(@name))"/> comp = (<value path="gen:toCamelCaseUpper(string(@name))"/>)o;

            //log.debug("this = " + this.toString());
            //log.debug("comp = " + comp.toString());
            //log.debug("this.<value path="gen:toCamelCase(string(@name))"/> = " + this.get<value path="gen:toCamelCaseUpper(string(@name))"/>());
            //log.debug("comp.<value path="gen:toCamelCase(string(@name))"/> = " + comp.get<value path="gen:toCamelCaseUpper(string(@name))"/>());

            boolean result = this.get<value path="gen:toCamelCaseUpper(string(@name))"/>().equals(comp.get<value path="gen:toCamelCaseUpper(string(@name))"/>());

            //log.debug("result = " + result);

            return result;
        }
        else
        {
            return false;
        }
    }

    public int hashCode()
    {
        return this.<value path="gen:toCamelCase(string(@name))"/>.hashCode();
    }

    public String toString()
    {
        return <value path="gen:toCamelCase(string(@name))"/>.toString();
    }
}

</compilationUnit>
</for>
</tl>

=== rupertlssmith/jenerator/catalogue-maven-plugin/src/resources/catalogue-facttable-bean.xml
<?xml version="1.0"?>
<tl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="C:\Documents and Settings\Rupert\projects\javasource\src\resources\tl.xsd"
    xmlns:cat="http://thesett.com/catalogue-def-0.2"
    xmlns:gen="http://thesett.com/source-code-generator-0.1">

<var name="package" value="cat:CatalogueDefinition/cat:Package/@name"/>

<for path="cat:CatalogueDefinition/cat:FactDef">
<compilationUnit package="$package" fileName="gen:toCamelCaseUpper(concat(string(@name), '.java'))">
package <value path="$package"/>;

import java.util.Date;
import java.io.Serializable;

/**
 * Generated fact table bean from catalogue model.
 */
public class <value path="gen:toCamelCaseUpper(string(@name))"/> implements Serializable
{
    public <value path="gen:toCamelCaseUpper(string(@name))"/>() {}

    private long id;

    private long getId()
    {
        return id;
    }

    private void setId(long id)
    {
        this.id = id;
    }

    <!-- Components need to be flattened. Views need to be catered for for conformed products. The extension mechanism
         for adding derived/calculated and other additional fields needs to be handled. -->
    <for path="cat:Component">
    private <value path="gen:toCamelCaseUpper(concat(string(@type), ' '))"/> <value path="gen:toCamelCase(string(@name))"/>;

    public <value path="gen:toCamelCaseUpper(string(@type))"/> get<value path="gen:toCamelCaseUpper(string(@name))"/>() { return <value path="gen:toCamelCase(string(@name))"/>; }
    public void set<value path="gen:toCamelCaseUpper(string(@name))"/>(<value path="gen:toCamelCaseUpper(concat(string(@type), ' '))"/> <value path="gen:toCamelCase(string(@name))"/>) { this.<value path="gen:toCamelCase(string(@name))"/> = <value path="gen:toCamelCase(string(@name))"/>; }
    
    </for>

    <for path="cat:String">
    private String <value path="gen:toCamelCase(string(@name))"/>;

    public String get<value path="gen:toCamelCaseUpper(string(@name))"/>() { return <value path="gen:toCamelCase(string(@name))"/>; }
    public void set<value path="gen:toCamelCaseUpper(string(@name))"/>(String <value path="gen:toCamelCase(string(@name))"/>) { this.<value path="gen:toCamelCase(string(@name))"/> = <value path="gen:toCamelCase(string(@name))"/>; }
    </for>

    <for path="cat:Integer">
    private int <value path="gen:toCamelCase(string(@name))"/>;

    public int get<value path="gen:toCamelCaseUpper(string(@name))"/>() { return <value path="gen:toCamelCase(string(@name))"/>; }
    public void set<value path="gen:toCamelCaseUpper(string(@name))"/>(int <value path="gen:toCamelCase(string(@name))"/>) { this.<value path="gen:toCamelCase(string(@name))"/> = <value path="gen:toCamelCase(string(@name))"/>; }
    </for>

    <for path="cat:Real">
    private float <value path="gen:toCamelCase(string(@name))"/>;

    public float get<value path="gen:toCamelCaseUpper(string(@name))"/>() { return <value path="gen:toCamelCase(string(@name))"/>; }
    public void set<value path="gen:toCamelCaseUpper(string(@name))"/>(float <value path="gen:toCamelCase(string(@name))"/>) { this.<value path="gen:toCamelCase(string(@name))"/> = <value path="gen:toCamelCase(string(@name))"/>; }
    </for>

    <for path="cat:Date">
    private Date <value path="gen:toCamelCase(string(@name))"/>;

    public Date get<value path="gen:toCamelCaseUpper(string(@name))"/>() { return <value path="gen:toCamelCase(string(@name))"/>; }
    public void set<value path="gen:toCamelCaseUpper(string(@name))"/>(Date <value path="gen:toCamelCase(string(@name))"/>) { this.<value path="gen:toCamelCase(string(@name))"/> = <value path="gen:toCamelCase(string(@name))"/>; }
    </for>

    <for path="cat:Time">
    private long <value path="gen:toCamelCase(string(@name))"/>;

    public long get<value path="gen:toCamelCaseUpper(string(@name))"/>() { return <value path="gen:toCamelCase(string(@name))"/>; }
    public void set<value path="gen:toCamelCaseUpper(string(@name))"/>(long <value path="gen:toCamelCase(string(@name))"/>) { this.<value path="gen:toCamelCase(string(@name))"/> = <value path="gen:toCamelCase(string(@name))"/>; }
    </for>

    <for path="cat:Hierarchy">
    <value path="gen:toCamelCaseUpper(concat(string(@type), ' '))"/> <value path="gen:toCamelCase(string(@name))"/>;

    public <value path="gen:toCamelCaseUpper(string(@type))"/> get<value path="gen:toCamelCaseUpper(string(@name))"/>() { return <value path="gen:toCamelCase(string(@name))"/>; }
    public void set<value path="gen:toCamelCaseUpper(string(@name))"/>(<value path="gen:toCamelCaseUpper(concat (string(@type), ' '))"/> <value path="gen:toCamelCase(string(@name))"/>){ this.<value path="gen:toCamelCase(string(@name))"/> = <value path="gen:toCamelCase(string(@name))"/>; }
    </for>
}

</compilationUnit>
</for>
</tl>

=== rupertlssmith/jenerator/catalogue-maven-plugin/src/resources/catalogue-hierarchy-usertype.xml
<?xml version="1.0"?>
<tl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="C:\Documents and Settings\Rupert\projects\javasource\src\resources\tl.xsd"
    xmlns:cat="http://thesett.com/catalogue-def-0.2"
    xmlns:gen="http://thesett.com/source-code-generator-0.1">

<var name="package" value="cat:CatalogueDefinition/cat:Package/@name"/>

<for path="cat:CatalogueDefinition/cat:HierarchyDef">
<compilationUnit package="$package" fileName="gen:toCamelCaseUpper(concat(string(@name), 'UserType.java'))">
package <value path="$package"/>;

import com.thesett.catalogue.customtypes.HierarchyAttributeCompositeUserType;
import com.thesett.aima.attribute.impl.HierarchyAttribute;

/**
 * Generated user hierarchy type from catalogue model.
 */
public class <value path="gen:toCamelCaseUpper(string(@name))"/>UserType extends HierarchyAttributeCompositeUserType
{
    public String[] getPropertyNames()
    {
        // Ensure that the hierarchy attribute type has been set up with its level names.
        HierarchyAttribute.getFactoryForClass(getTypeName()).setLevelNames(new String[] { <for path=".//cat:Level">"<value path="@name"/>"<if path="gen:notLastInFor()">, </if></for> });

        return super.getPropertyNames();
 
    }

    public String getTypeName()
    {
        return "<value path="@name"/>";
    }
}

</compilationUnit>
</for>
</tl>

=== rupertlssmith/jenerator/catalogue-maven-plugin/src/resources/catalogue-enumeration-bean.xml
<?xml version="1.0"?>
<tl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="C:\Documents and Settings\Rupert\projects\javasource\src\resources\tl.xsd"
    xmlns:cat="http://thesett.com/catalogue-def-0.2"
    xmlns:gen="http://thesett.com/source-code-generator-0.1">

<var name="package" value="cat:CatalogueDefinition/cat:Package/@name"/>

<for path="cat:CatalogueDefinition/cat:EnumerationDef">
<compilationUnit package="$package" fileName="gen:toCamelCaseUpper(concat(string(@name), '.java'))">
package <value path="$package"/>;

import java.io.Serializable;

import org.apache.log4j.Logger;

import com.thesett.aima.attribute.impl.EnumeratedStringAttribute;
import com.thesett.aima.state.impl.ExtendableBeanState;

/**
 * Generated enumeration bean from catalogue model.
 */
public class <value path="gen:toCamelCaseUpper(string(@name))"/> extends ExtendableBeanState implements Serializable
{
    /** Used for logging. */
    private static final Logger log = Logger.getLogger(<value path="gen:toCamelCaseUpper(string(@name))"/>.class);

    private EnumeratedStringAttribute <value path="@name"/>;

    /** No-arg constructor for serialization. */
    public <value path="gen:toCamelCaseUpper(string(@name))"/>() {}

    public <value path="gen:toCamelCaseUpper(string(@name))"/>(EnumeratedStringAttribute h) { this.<value path="@name"/> = h; }

    public <value path="gen:toCamelCaseUpper(string(@name))"/>(String value)
    {
        EnumeratedStringAttribute.EnumeratedStringAttributeFactory factory = EnumeratedStringAttribute.getFactoryForClass("<value path="@name"/>");

        <value path="@name"/> = factory.createStringAttribute(value);
    }

    private Long getId()
    {
        if (<value path="@name"/> != null)
        {
            return <value path="@name"/>.getId();
        }
        else
        {
            return null;
        }
    }

    private void setId(Long id)
    {
        if (<value path="@name"/> != null)
        {
            <value path="@name"/>.setId(id);
        }
    }

    public EnumeratedStringAttribute get<value path="gen:toCamelCaseUpper(string(@name))"/>()
    {
        return <value path="@name"/>;
    }

    public void set<value path="gen:toCamelCaseUpper(string(@name))"/>(EnumeratedStringAttribute h)
    {
        <value path="@name"/> = h;
    }

    public boolean equals(Object o)
    {
        log.debug("public boolean equals(Object o): called");

        if (o instanceof <value path="gen:toCamelCaseUpper(string(@name))"/>)
        {
            <value path="gen:toCamelCaseUpper(string(@name))"/> comp = (<value path="gen:toCamelCaseUpper(string(@name))"/>)o;

            //log.debug("this = " + this.toString());
            //log.debug("comp = " + comp.toString());
            //log.debug("this.<value path="@name"/> = " + this.get<value path="gen:toCamelCaseUpper(string(@name))"/>());
            //log.debug("comp.<value path="@name"/> = " + comp.get<value path="gen:toCamelCaseUpper(string(@name))"/>());

            boolean result = this.get<value path="gen:toCamelCaseUpper(string(@name))"/>().equals(comp.get<value path="gen:toCamelCaseUpper(string(@name))"/>());

            //log.debug("result = " + result);

            return result;
        }
        else
        {
            return false;
        }
    }

    public int hashCode()
    {
        return this.<value path="@name"/>.hashCode();
    }

    public String toString()
    {
        return <value path="@name"/>.toString();
    }
}

</compilationUnit>
</for>
</tl>
